In [1]:
import numpy as np
from plain import Plain
from food import Food

In [2]:
np.array([2,2]) - 1

array([1, 1])

In [3]:
f = Food(plain = Plain(15,15), snake_location=np.array([[1,1], [1,2], [2,2], [3,2], [4,2]]))

[[ 6 14]]


In [4]:
testplain = Plain(15, 15)

In [10]:
testplain.gameplain

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [ ]:
testplain.gameplain[np.array([])]

IndexError: index 20 is out of bounds for axis 0 with size 17

In [154]:
np.stack(np.meshgrid(np.arange(1, 16), np.arange(1,16))).shape

(2, 15, 15)

In [167]:
np.__version__

'2.0.0'

In [ ]:
np.stack(np.meshgrid(np.arange(1, 16), np.arange(1,16)), axis = 2)

(15, 15, 2)

In [192]:
np.reshape(np.stack(np.meshgrid(np.arange(1, 16), np.arange(1,16)), axis = 2), newshape=(15**2, 2))

array([[ 1,  1],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  1],
       [ 8,  1],
       [ 9,  1],
       [10,  1],
       [11,  1],
       [12,  1],
       [13,  1],
       [14,  1],
       [15,  1],
       [ 1,  2],
       [ 2,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  2],
       [11,  2],
       [12,  2],
       [13,  2],
       [14,  2],
       [15,  2],
       [ 1,  3],
       [ 2,  3],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  3],
       [ 9,  3],
       [10,  3],
       [11,  3],
       [12,  3],
       [13,  3],
       [14,  3],
       [15,  3],
       [ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 4,  4],
       [ 5,  4],
       [ 6,  4],
       [ 7,  4],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  4],
       [13,  4],
       [14,  4

In [193]:
tt = np.reshape(np.stack(np.meshgrid(np.arange(1, 16), np.arange(1,16)), axis = 2), newshape=(15**2, 2))

In [195]:
tt

array([[ 1,  1],
       [ 2,  1],
       [ 3,  1],
       [ 4,  1],
       [ 5,  1],
       [ 6,  1],
       [ 7,  1],
       [ 8,  1],
       [ 9,  1],
       [10,  1],
       [11,  1],
       [12,  1],
       [13,  1],
       [14,  1],
       [15,  1],
       [ 1,  2],
       [ 2,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  2],
       [11,  2],
       [12,  2],
       [13,  2],
       [14,  2],
       [15,  2],
       [ 1,  3],
       [ 2,  3],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  3],
       [ 9,  3],
       [10,  3],
       [11,  3],
       [12,  3],
       [13,  3],
       [14,  3],
       [15,  3],
       [ 1,  4],
       [ 2,  4],
       [ 3,  4],
       [ 4,  4],
       [ 5,  4],
       [ 6,  4],
       [ 7,  4],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  4],
       [13,  4],
       [14,  4

In [220]:
tt[np.all(tt != np.array([[2,1]]), axis = 1)]

array([[ 1,  2],
       [ 3,  2],
       [ 4,  2],
       [ 5,  2],
       [ 6,  2],
       [ 7,  2],
       [ 8,  2],
       [ 9,  2],
       [10,  2],
       [11,  2],
       [12,  2],
       [13,  2],
       [14,  2],
       [15,  2],
       [ 1,  3],
       [ 3,  3],
       [ 4,  3],
       [ 5,  3],
       [ 6,  3],
       [ 7,  3],
       [ 8,  3],
       [ 9,  3],
       [10,  3],
       [11,  3],
       [12,  3],
       [13,  3],
       [14,  3],
       [15,  3],
       [ 1,  4],
       [ 3,  4],
       [ 4,  4],
       [ 5,  4],
       [ 6,  4],
       [ 7,  4],
       [ 8,  4],
       [ 9,  4],
       [10,  4],
       [11,  4],
       [12,  4],
       [13,  4],
       [14,  4],
       [15,  4],
       [ 1,  5],
       [ 3,  5],
       [ 4,  5],
       [ 5,  5],
       [ 6,  5],
       [ 7,  5],
       [ 8,  5],
       [ 9,  5],
       [10,  5],
       [11,  5],
       [12,  5],
       [13,  5],
       [14,  5],
       [15,  5],
       [ 1,  6],
       [ 3,  6],
       [ 4,  6

In [236]:
len([i for i in tt if i.tolist() not in np.array([[1,1], [1,2], [2,2], [3,2], [4,2]]).tolist()])

220

In [231]:
np.isin(tt, np.array([[1,1], [1,2], [2,2], [3,2], [4,2]]))

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [False,  True],
       [Fal

In [29]:
np.any(np.array([2,2]) == np.array([1,1]))

np.False_